Here we will learn the basics of the Julia Programming language.

How fast you can get the idea in you into a code, Julia will help you with this

This link is to get an initial motivation for why to use Julia
https://www.youtube.com/watch?v=qGW0GT1rCvs

Here we wuill use teh tutorial available in the following link

https://www.youtube.com/watch?v=Fi7Pf2NveH0

# 1. Basic Julia

All julia operations return a value

In [1]:
x = 3

3

we can slilence the printing the value by adding ;

In [12]:
x = 3;

In [3]:
y = 2^3 # powers

8

we can use LaTeX syntax for hte corresponding unicode character

In [7]:
δ = "I am delta" # press \delta and then press TAB 

"I am delta"

In [11]:
😸 = 2

2

updating a vlue

In [19]:
x=3

3

In [20]:
x += 4

7

In [21]:
x -= 2

5

In [23]:
x *= 2

10

In [24]:
x /=3

3.3333333333333335

We donot need to use the * sign to multiply the variables with numbers

In [25]:
x = 2
y = 3;

In [27]:
5x + 3y

19

to understand the type of the variables

In [28]:
typeof(😸)

Int64

In [29]:
typeof("dasd")

String

To convert the value of the varable to the string (we use this in print usually)

In [31]:
print("the value of ex is: $(x)")

the value of ex is: 2

We can also do any kind of operations inside $ symbol ans then print

In [33]:
print("the value is $(2x^2 + 3y + 45)")

the value is 62

In [38]:
"$(x+2y)"

"8"

## Basic Collections

INdexing is done with brackets:
`collection[index]`. 

#### *Julia indexing start from 1*

### Tuples

Tuples are immutable collections of elements. They are mostly used when the elemenets are not of the same type with each other and are intended for small collections. 

Syntax:
`(item1, item2,...)`

In [39]:
my_things = ("purple","cats", π)

("purple", "cats", π)

In [44]:
my_things[1]   # first collections

"purple"

In [43]:
my_things[2]

"cats"

### Names tuples


They are exactly like tuples but you can also assigna  name to the each variable in it. 
The syntax is:

`(key = val1, key2 = val2,...)`

In [45]:
nt = (surname="kusampudi", name="Navyanth", age=29)

(surname = "kusampudi", name = "Navyanth", age = 29)

In [57]:
nt[1]  # accesing the namedd tuples through index

"kusampudi"

In [58]:
nt.surname # accesing the namedd tuples through keys

"kusampudi"

In [59]:
nt[:surname]

"kusampudi"

### Dictionaries

when we hvae stuff of same type

syntax: 

`Dict(key1 => value1, key2=>value2, ....)`

In [67]:
ages = Dict("shar_age" =>29,"navy_age"=>29, "lilli_age"=>21)

Dict{String,Int64} with 3 entries:
  "navy_age"  => 29
  "shar_age"  => 29
  "lilli_age" => 21

In [68]:
ages["shar_age"]

29

New items can aslo be added to the dictionary as dictionary is mutable (You can change its values)

In [69]:
ages["kari_age"] = 21

21

In [70]:
ages

Dict{String,Int64} with 4 entries:
  "kari_age"  => 21
  "navy_age"  => 29
  "shar_age"  => 29
  "lilli_age" => 21

Remenber tha telements and keys have to be of same type

### Arrays

In Julia `Array` is a mutable and ordered collection of items of same type. `Matrix` is of dimension 2 and `vector` is of dimension 1. i.e a vector of vectors of num,bers and a matrix of numbers are two totally different things

syntax:

`[item1, item2,...]`

In [73]:
my_frinds = ["sharan", "lilli", "kari", "johnas", "nadim"]  # array of strings

5-element Array{String,1}:
 "sharan"
 "lilli"
 "kari"
 "johnas"
 "nadim"

In [74]:
ages  = [28,22,21,21,20]

5-element Array{Int64,1}:
 28
 22
 21
 21
 20

The above output shows `Array{TypeOfThings, Dimensionality}`

Arrays of other data structures, eg. Vectors or dictionaries or anythong as well as multi dimensionla arrays is possible

In [75]:
a = [[1,2],[3,4],[5,6]]

3-element Array{Array{Int64,1},1}:
 [1, 2]
 [3, 4]
 [5, 6]

The element tof the vector is a vecor in itself

IF we want to adda matrix, 

**1. Specify each entry one by one**

In [79]:
matrix = [1 2 3;                    # elements in same row seperated by space
          4 5 6;                     # semicolum to go to next row
          7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

#### 2. Use a function that initializes a matrix. 

example `rand(n,m)` will create an `nxm` matrix of  uniformly random numbers

In [80]:
random_matrix = rand(2,3)

2×3 Array{Float64,2}:
 0.0915482  0.744406  0.102747
 0.272404   0.159387  0.00672266

In [98]:
zeros(3,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [99]:
ones(2,2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

Indexing the matrix elements

In [102]:
random_matrix[1,1]

0.09154816922256837

In [82]:
random_matrix[1,2]

0.7444064399501047

since arrays and matrices are mutalble this meaans we can add, remove, chmage the elemts

In [90]:
fibonachi = [1,1,2,3,5,8,13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [91]:
fibonachi[1] = 15

15

In [92]:
push!(fibonachi,16)   # adding the number to the array

8-element Array{Int64,1}:
 15
  1
  2
  3
  5
  8
 13
 16

In [94]:
pop!(fibonachi)

16

In [95]:
fibonachi

7-element Array{Int64,1}:
 15
  1
  2
  3
  5
  8
 13

`push!` and `pop!` are help you to add or remove the last element of teh array

We can use `:` symbol to select all elements in a dimension

In [96]:
x = rand(3,3)

3×3 Array{Float64,2}:
 0.312304    0.706538  0.971675
 0.709839    0.741432  0.939983
 0.00865203  0.478102  0.104078

In [97]:
x[:,1]

3-element Array{Float64,1}:
 0.3123042429114331
 0.7098394951883069
 0.0086520317298453

### Ranges

Ranges are useful short and notations that define a "vector"

syntax: 

`start:step:end
range(start, end; length = ...)
range(start, end; step = ..)`

In [109]:
r = 0:1:10

0:1:10

As ranges are printed in short form, to see all their elements you can use the `collect` function to transform the range into a `Vector`

In [110]:
collect(r)

11-element Array{Int64,1}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

range is not a vector; they do not store all the varaibles in the memory.

Ranges are also helpful to index tono arrays. 

In [114]:
A = rand(3,3)

3×3 Array{Float64,2}:
 0.827455  0.291813  0.0503247
 0.403448  0.155464  0.926899
 0.269794  0.779201  0.89961

In [119]:
A[1:3]    # first element in three rows

3-element Array{Float64,1}:
 0.8274545003490528
 0.4034478962126409
 0.26979432455307983

In [118]:
A[1:3,1]

3-element Array{Float64,1}:
 0.8274545003490528
 0.4034478962126409
 0.26979432455307983

In [117]:
A[1:2,1:2]

2×2 Array{Float64,2}:
 0.827455  0.291813
 0.403448  0.155464

### List comprehension

the list comprehension syntax 

`[expression(a) for a in collection if condition(a)]`

In [120]:
[a^2 for a in 1:10]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [121]:
[a^2 for a in 1:10 if iseven(a)]

5-element Array{Int64,1}:
   4
  16
  36
  64
 100

## Iterations

### `for` loops

syntax

`for *var* in *loop iterable*
     *loop body
 end
`

In [123]:
for n in 1:5
    print(n)
end

12345

In [124]:
for n in 1:5
    println(n)
end

1
2
3
4
5


We can also use the mathematical symbol $\in$ in place of `in`

In [126]:
for n ∈ 1:5
    println(n)
end

1
2
3
4
5


The value of `var` depends on what the iterating container has. For example when iterating over a dictionary one iterates overa paris of key-value

In [127]:
ages = Dict("shar_age" =>29,"navy_age"=>29, "lilli_age"=>21)

Dict{String,Int64} with 3 entries:
  "navy_age"  => 29
  "shar_age"  => 29
  "lilli_age" => 21

In [129]:
for (key, val) in ages
    println("$key is $val")
end

navy_age is 29
shar_age is 29
lilli_age is 21


In [132]:
for pair in ages                 
    println("$(pair[1]) is $(pair[2])")
end

navy_age is 29
shar_age is 29
lilli_age is 21


### `while` loops

They execute a condition untill a condition is true

Syntax:

```python
while *condition*
      * loop body*
end
```

In [133]:
n = 0

while n < 5
    n += 1
    println(n)
end

1
2
3
4
5


## Conditionals

syntax

```python

if *condition 1*
    *option 1*
    
elseif *condition 2*
    *option 2*
    
else *condition 3*
    *option 3*
    
end

```

In [134]:
navy_age = 28

if navy_age <=19
    print("navy is a teenager")
    
elseif navy_age >=30
    print("navy is an uncle")
    
else navy_age
    print("navy is still young")
    
end

navy is still young

### with terenary operators

For this last block we could use the terenary operator with the syntax

`a ? b :c`

which is equals to

```python
if a
    b
else
    c
end
```

In [139]:
x = 10
y = 12

x > y ? x : y    # if x> y give me x otherwise giveme y

12

In [142]:
x = 10
y = 11
z = 12

x > y ? 9 : (z<10 ? 30 : 40)   # two nested `if` loops

40

### `break` and `continue` 

They can be used to skip and iteration or aompletely stop the iteration code block

In [144]:
N = 1:10

for n in N
    isodd(n) && continue        # if number is odd we skip the iteration
    println(n)
end

2
4
6
8
10


In [145]:
N = 1:20

for n in N
    isodd(n) && continue        # if number is odd we skip the iteration
    println(n)
    n > 10 && break             # if number is greater than 10, completely break the itearation
end

2
4
6
8
10
12


## Functions